# Generated by Django 4.2 on 2023-04-26 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_person_id_alter_trains_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
