# Generated by Django 4.2 on 2023-04-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_trains_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
